### ISSUE TITLE
Ansible 2.10.0 and 1.0.0 before 2020-08-18

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.grafana#111]
As im active in the Zabbix Collection we there got the following message from @gundalow :

“The 2020-08-18 date is of particular importance. This means that by that day, you MUST have released 1.0.0 for it to appear in Ansible 2.10. If you only have a 0.x.y release by then, we will not automatically include a newer version since according to semver, anything can happen and no stability guarantees are made. So please make sure that you released 1.0.0 by then.”

Just wanted to drop it here if you haven't heard.

**Comment by rrey** [comment]
Ha nice! Thx for the info
I think we can release it right now !

**Comment by rockaut** [comment]
You're welcome.
Can you wait so that I can get the pr I've opened incorporated please? Would be appreciated.

**Comment by rockaut** [comment]
Ok... I now implemented #108 in a safe/backward compatible way. So this is a go for me.
#104 is failing with some sanity tests. Maybe one can look into it - I don't understand why it's failing while a run for #108 is not failing - I miss something here.

Other than that I have some more changes incoming in the next weeks but nothing which is blocking. Thank you.

**Comment by rockaut** [comment]
Leaving this here too:

1) The Bullhorn (the Ansible Contributor newsletter) https://us19.campaign-archive.com/home/?u=56d874e027110e35dea0e03c1&id=d6635f5420
2) Changes impacting Contributors ansible-collections/overview#45

**Comment by rockaut** [comment]
I figured out the sanity errors: they came from version_added proberties (in doc and modules) as they where still for the ansible release. They now should be hinting to collection release version. I've changed all of them to '1.0.0'.

**Comment by rrey** [comment]
I'm closing this issue in favor of #112. Thanks @rockaut for raising this in advance.
