### ISSUE TITLE
grafana_dashboard not idempotent

### ISSUE THREAD

**Issue by axxeo** [ansible-collections/community.grafana#122]
##### SUMMARY
Running the grafana_dashboard module (with same args) results in changed=True, when no uid is given.

When you create a dashboard without the argument 'uid' grafana will generate one.
This results in changed=True.

A possible solution would be to ignore the uid key in grafana_dashboard_changed() in grafana_dashboard.py
```
if 'uid' not in payload['dashboard'] and 'uid' in dashboard['dashboard']:
        del(dashboard['dashboard']['uid'])
```

**Comment by rrey** [comment]
Hi @axxeo 

The uuid is the safe method to retrieve a dashboard. The dashboard name can be updated and is not a safe key to retrieve it.
The Json that you use should contain an uuid if you exported it from Grafana after you created it.

**Comment by rrey** [comment]
Closing this issue without feedback.
