### ISSUE TITLE
Invalid removal version according to semantic versioning

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.grafana#131]
##### SUMMARY
The `commit_message` option of `grafana_dashboard` is depreated with removal version community.grafana 2.14.0. According to [semantic versioning](https://semver.org/), breaking changes in the API can only be made in major versions, while 2.14.0 is a minor release.

I'd suggest you either change 2.14.0 to 2.0.0, or to 3.0.0, depending what your versioning plans are for community.grafana.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_dashboard

**Comment by rrey** [comment]
Thanks for pointing that out @felixfontein !
