### ISSUE TITLE
alerting notification channel support

### ISSUE THREAD

**Issue by ikke-t** [ansible-collections/community.grafana#137]
##### SUMMARY

As a user I want to be able to define alerts which now miss notification channel setting via ansible.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Probably missing such module. Settings module?

##### ADDITIONAL INFORMATION

Now I manage to create dashboards, which also has alerts. But all alerts are missing notification channel (email, chat, etc...) definition, so they won't get sent. I copied a dashboard with alert from manually created grafana. When I push that dashboard to new instance, it complains about not having alert notification channel. And that is missing from the new grafana.

**Comment by rrey** [comment]
Hi @ikke-t !

The module does not exists indeed. That would be a `grafana_notification_channel` I guess.
API documentation link for latest Grafana version : https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels

**Comment by ikke-t** [comment]
Thanks, works nicely!
