### ISSUE TITLE
Can't create folder on Grafana 7.3.7 stable (tried 7.1.3 as well, same issue)

### ISSUE THREAD

**Issue by gacallea** [ansible-collections/community.grafana#147]
##### SUMMARY
Trying to create "named folders" and upload "named dashboards" to them.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.grafana.grafana_folder

##### ANSIBLE VERSION
```paste below
ansible --version
ansible 2.10.5
  config file = /Users/xxx/yada/yada/ansible.cfg
  configured module search path = ['/Users/xxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Jan 30 2021, 15:51:59) [Clang 12.0.0 (clang-1200.0.32.29)]
```

##### CONFIGURATION
```paste below

```

##### OS / ENVIRONMENT
Ubuntu 20.04
Grafana 7.3.7 stable -- installed from the official Grafana repository (oss stable)

##### STEPS TO REPRODUCE
Posting the relevant tasks only. All variables work in other tasks. The upload to /tmp/dashboard is omitted here.

```yaml
- name: "Create {{ pool_ticker }} folder"
  community.grafana.grafana_folder:
    state: present
    name: "{{ pool_ticker }}"
    url: "https://{{ grafana_domain }}"
    url_username: "{{ grafana_admin_user }}"
    url_password: "{{ grafana_admin_pass }}"

- name: "Import {{ pool_ticker }} Metrics v1 Dashboard"
  community.grafana.grafana_dashboard:
    dashboard_revision: "1"
    folder: "{{ pool_ticker }}"
    path: "/tmp/{{ pool_ticker }}-PoolMetricsV1.json"
    grafana_url: "https://{{ grafana_domain }}"
    url_username: "{{ grafana_admin_user }}"
    url_password: "{{ grafana_admin_pass }}"
```

##### EXPECTED RESULTS
a folder with a ticker name should be created.
a ticker named dashboard should be uploaded to the above folder.

##### ACTUAL RESULTS

```paste below
fatal: [spaas-mon]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 142.93.43.238 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/igghibu/.ansible/tmp/ansible-tmp-1612433673.381998-67602-133808153941091/AnsiballZ_grafana_folder.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/igghibu/.ansible/tmp/ansible-tmp-1612433673.381998-67602-133808153941091/AnsiballZ_grafana_folder.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/igghibu/.ansible/tmp/ansible-tmp-1612433673.381998-67602-133808153941091/AnsiballZ_grafana_folder.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.grafana.plugins.modules.grafana_folder', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.grafana.grafana_folder_payload_ybp_mas9/ansible_community.grafana.grafana_folder_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_folder.py\", line 274, in <module>\r\n  File \"/tmp/ansible_community.grafana.grafana_folder_payload_ybp_mas9/ansible_community.grafana.grafana_folder_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_folder.py\", line 254, in main\r\n  File \"/tmp/ansible_community.grafana.grafana_folder_payload_ybp_mas9/ansible_community.grafana.grafana_folder_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_folder.py\", line 178, in __init__\r\n  File \"/tmp/ansible_community.grafana.grafana_folder_payload_ybp_mas9/ansible_community.grafana.grafana_folder_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_folder.py\", line 208, in get_version\r\nAttributeError: 'NoneType' object has no attribute 'split'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by rrey** [comment]
Tested locally through docker and integration tests.
The endpoint returns a legit version:
```
$ curl 127.0.0.1:3000/api/health
{
  "commit": "1e261642f4",
  "database": "ok",
  "version": "7.3.7"
}
```

And the folder is properly created.
I also:
- tested outside the test environment of the collection with what `ansible 2.10.5` comes with: it worked.
- Installed latest collection version through ansible galaxy : it worked


I'm failing at reproducing @gacallea. Can you post the output of a curl command on `curl http://your_grafana/api/health` ?
Thanks

**Comment by gacallea** [comment]
@rrey it returns only this:

```
{
  "database": "ok"
}
```

**Comment by rrey** [comment]
well that's unexpected ...

**Comment by gacallea** [comment]
> well that's unexpected ...

do I need to enable anything api related in the grafana.ini perhaps?

while this is unexpected every other ansible grafana task works. I'm puzzled.

**Comment by rrey** [comment]
Not all modules checks the version. Only the one that are addressing feature introduced after a specific version.
I’m discovering the fact that the health endpoint could not return the version. It would be worth asking Grafana people about this.
Meanwhile we could fallback to consider the version compatible if we don’t get any version

**Comment by gacallea** [comment]
I'm investigating and apparently one needs to be authenticated to get more info from the health api. If I run the curl locally or visit the page, it only returns the dashboard. I'll try authenticating the request and come back to you. That being said, it's weird because the tasks should clearly be authenticated with url_user and url_password.

Regarding the compatible version, I tried downgrading to 7.1.3 because the readme on community grafana lists it as supported. Same issues.

**Comment by gacallea** [comment]
Ok, I found the settings. Under [auth.anonymous] there's a hide_version = true that will not output version and commit. I set this not to disclose info to non-authenticated users for security reasons, and tools should probably not rely on this info as many could choose to hide this info as well as a best practice.

However, I have enabled it to debug the issue and now it returns the following:

```
{
  "commit": "1e261642f4",
  "database": "ok",
  "version": "7.3.7"
}
```

Also, I tried running the tasks now that this is in place and:

- the folders are now created
- but the dashboard fails installing in the created folders. 

I'm currently trying to understand why that is. Here's the error:

```
fatal: [spaas-mon]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 142.93.43.238 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/igghibu/.ansible/tmp/ansible-tmp-1612788860.215988-33854-205748372882357/AnsiballZ_grafana_dashboard.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/igghibu/.ansible/tmp/ansible-tmp-1612788860.215988-33854-205748372882357/AnsiballZ_grafana_dashboard.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/igghibu/.ansible/tmp/ansible-tmp-1612788860.215988-33854-205748372882357/AnsiballZ_grafana_dashboard.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.grafana.plugins.modules.grafana_dashboard', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.grafana.grafana_dashboard_payload_dmqg_qd0/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py\", line 563, in <module>\r\n  File \"/tmp/ansible_community.grafana.grafana_dashboard_payload_dmqg_qd0/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py\", line 525, in main\r\n  File \"/tmp/ansible_community.grafana.grafana_dashboard_payload_dmqg_qd0/ansible_community.grafana.grafana_dashboard_payload.zip/ansible_collections/community/grafana/plugins/modules/grafana_dashboard.py\", line 380, in grafana_create_dashboard\r\nKeyError: 'commit_message'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by gacallea** [comment]
perhaps a possible solution could be for grafana_folder to actually use url_user and url_password to use authentication when checking the health api for version instead of relying on non auth queries?

**Comment by rrey** [comment]
> perhaps a possible solution could be for grafana_folder to actually use url_user and url_password to use authentication when checking the health api for version instead of relying on non auth queries?

The request already use the the authentication headers to access this endpoint.
We could drop the control on the version since the module docs states that a Grafana version > 5 is required for folders.

**Comment by gacallea** [comment]
> > perhaps a possible solution could be for grafana_folder to actually use url_user and url_password to use authentication when checking the health api for version instead of relying on non auth queries?
> 
> The request already use the the authentication headers to access this endpoint.
> We could drop the control on the version since the module docs states that a Grafana version > 5 is required for folders.

sounds like a plan :) 

should I open a new request for that to happen? you take care of it?

thank you for all your help, I appreciate you.

**Comment by rrey** [comment]
@gacallea I'll keep the version check but I'll add a parameter that allow to skip the control.
You'll just have to enable the parameter in the module call.

**Comment by gacallea** [comment]
thank you so much @rrey!!! I appreciate you :)

about using it, will the documentation update automatically (like with a doc generator from code?)

an example would be nice otherwise. please and thank you

**Comment by gacallea** [comment]
ps: this should work?

```
- name: "Create PRIVATE folder"
  community.grafana.grafana_folder:
    skip_version_check: yes
    state: present
    name: "Private"
    url: "https://{{ grafana_domain }}"
    url_username: "{{ grafana_admin_user }}"
    url_password: "{{ grafana_admin_pass }}"
```

**Comment by rrey** [comment]
Doc update is in the hand of ansible team.
But your code sample is exactly what you should do.
New collection (v1.2.0) was published, let me know about the results

**Comment by gacallea** [comment]
> Doc update is in the hand of ansible team.
> But your code sample is exactly what you should do.
> New collection (v1.2.0) was published, let me know about the results

it worked fine :) (I re-enabled the hide version thingie)
