### ISSUE TITLE
Can't load dashboard json file

### ISSUE THREAD

**Issue by gaetanBelliere** [ansible-collections/community.grafana#191]
##### SUMMARY

While trying to provision a CentOS7 VM with Ansible, some dashboards configuration files fail to load. Those json files are fetched from the grafana GUI. The dashboards that fail are dashboards containing Markdown Text panel. Issue is the following : 
```
failed: [gx-artifactory-dev] (item={'path': '/data/grafana/Endurance/endurance-home-page.json', 'folder': 'Endurance'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "Endurance", "path": "/data/grafana/Endurance/endurance-home-page.json"}, "msg": "error : Can't load json file 'ascii' codec can't decode byte 0xe2 in position 3872: ordinal not in range(128)"}
```
One quick fix is to convert the text to HTML with appropriate flags.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

grafana_dashboard

##### ANSIBLE VERSION

```
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 2.11.2
  libyaml = True
```

##### COLLECTION VERSION

```
community.grafana             1.2.3

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

The targeted os is a CentOS7 local VM. I use a Windows docker container as an Ansible runner.

##### STEPS TO REPRODUCE

Create a grafana dashboard with a Mardown text panel.
Copy the json model of the dashboard and store it in dashboard.json.
Provision grafana dashboard.
 

```
- name: Import Grafana dashboards
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana_localhost }}"
    state: present
    path: dashboard.json
    overwrite: yes
    folder: Global  
    commit_message: "Updated by Ansible"
    url_password: "{{ grafana_password_for_admin }}"
```

##### EXPECTED RESULTS

The dashboard to load and to be provision like other dashboards with no markdown text.

##### ACTUAL RESULTS

Dashboard fails to load

```
failed: [gx-artifactory-dev] (item={'path': '/data/grafana/Endurance/endurance-home-page.json', 'folder': 'Endurance'}) => {"ansible_loop_var": "item", "changed": false, "item": {"folder": "Endurance", "path": "/data/grafana/Endurance/endurance-home-page.json"}, "msg": "error : Can't load json file 'ascii' codec can't decode byte 0xe2 in position 3872: ordinal not in range(128)"
```
I know how to fix this bug. I have tested it locally. Thanks to this post : https://stackoverflow.com/questions/491921/unicode-utf-8-reading-and-writing-to-files-in-python/844443#844443

Here : https://github.com/ansible-collections/community.grafana/blob/main/plugins/modules/grafana_dashboard.py#L308 
Should be changed to : 
```
with io.open(data['path'], mode='r', encoding="utf-8") as json_file:
```
Of course import io at the top of the file.

**Comment by rrey** [comment]
@gaetanBelliere woud you be able to provide the dashboard that provoke the failure ? I wonder if I could add it in the tests.
I think that keeping the standard `open` function can work as well since it also have the encoding parameter support.

**Comment by gaetanBelliere** [comment]
What's weird is that when I tried to upload the conflicting files only it would work perfectly, making my example not relevant.. So instead I used the Grafana provisioning, which is way easier to maintain than using Ansible (because it doesn't require to keep an exact list of every dashboard config file and it's destination). I guess we can close this issue, even though the problem remains
