### ISSUE TITLE
grafana 8: notification channels not working

### ISSUE THREAD

**Issue by rrey** [ansible-collections/community.grafana#202]
Yup, that was exactly the case. Adding UID fixes it.

A bit unrelated to this issue is that Grafana replaced notification channels with so called "contact points". Ansible isn't borking when creating a notification channel but Grafana isn't translating that into a contact point. Which means it can't be used in Grafana itself. Also the configured notification channel is nowhere to be found in the GUI. Any ideas on that?

_Originally posted by @markri in https://github.com/ansible-collections/community.grafana/issues/189#issuecomment-995872526_

**Comment by rrey** [comment]
Starting Grafana 8.3 the notification channel is not more working and seems to fall under the "legacy dashboard alerts".

Problem: I don't see the API for the new contact points. Checking browser network traces I can see that the endpoint addressed is `/api/alertmanager/grafana/config/api/v1/alerts`.

First measure would be to document that the `grafana_notification_channel` is no more relevant starting 8.3.x

**Comment by Nemental** [comment]
deprecation of notification_channel #382 and added contact_point #352
