### ISSUE TITLE
Add documentation about grafana_user not supporting grafana_api_key authentication 

### ISSUE THREAD

**Issue by Lusitaniae** [ansible-collections/community.grafana#215]

**Comment by rrey** [comment]
Hello @Lusitaniae,

Nope, the api endpoint for users requires basic auth and admin privileges. See [mention in Grafana doc](https://grafana.com/docs/grafana/latest/http_api/user/#:~:text=parameter%20is%201.-,Requires%20basic%20authentication%20and%20that%20the%20authenticated%20user%20is%20a%20Grafana%20Admin.,-Example%20Response%3A)

**Comment by Lusitaniae** [comment]
Right, noticed that

Maybe we could document that requirement?

**Comment by rrey** [comment]
@Lusitaniae would you review the note I added in the module doc ? Thanks !
