### ISSUE TITLE
Updating CI

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.grafana#232]
##### SUMMARY
Dear maintainers,

Could anyone please:
- [x] Copy ignore-2.13.txt to ignore-2.14.txt as mentioned there https://github.com/ansible-collections/news-for-maintainers/issues/13

Also there were 2 other announcements recently that need maintainer attention:

- [x] https://github.com/ansible-collections/news-for-maintainers/issues/15
- [x] https://github.com/ansible-collections/news-for-maintainers/issues/14

When you create PRs, could you please put something like `Relates to <corresponding_issue>` so that it'll be easier for me to track repos that fixed CI (but please don't put `Fixes ...` as it'll close the issue).

Looking forward to your feedback,
Thanks!

**Comment by rrey** [comment]
thanks for the pointers @Andersson007 <3

**Comment by Andersson007** [comment]
@rrey thanks for solving the issue!
