### ISSUE TITLE
support grafana 9

### ISSUE THREAD

**Issue by lkwg82** [ansible-collections/community.grafana#254]
I've seen the code is already in place.

This is just a tracking issue and just need a release.

**Comment by lkwg82** [comment]
duplicate to #248 

did not see before, sry

**Comment by rrey** [comment]
Don’t hesitate to report issues, there are probably issues with grafana 9 and work has to be done

**Comment by lkwg82** [comment]
Thx. I've seen the fix in the code. So it was sth very specific.
