### ISSUE TITLE
Support for ES < 9.10 is dropped from Grafana 9.0.2

### ISSUE THREAD

**Issue by markri** [ansible-collections/community.grafana#263]
In Grafana 9.0.3, the support for Elasticsearch < 9.10 is dropped. Meaning that we can't create an ES datasource anymore as the dictionary prohibits the use of anything like that (on module 1.5.0)

`es_version=dict(type='int', default=710, choices=[2, 5, 56, 60, 70]),`

In Grafana 9.0.3 you have now 2 options, 7.10+ and 8.0+. Via API provisioning (I know because of exporting the datasource from grafana) you need to enter "7.10.0" to get it to 7.10+, but this is not an integer. So some typecasting needs to be done until a string "7.10.0" is put into esVersion on the actual call.

**Comment by rrey** [comment]
@markri I have a hotfix in review, I added an integration test that attempts to create a datasource with "7.10+" elastic version. The API and the WUI looks to reflect something that worked, but I would be happy if you could test with your real use case.

The Grafana Api has the tendancy to accepts things that are not really working and I don't have a real elactic instance running in my integration tests :/

**Comment by markri** [comment]
Hi @rrey I just confirmed that everything is working now. Thanks!

I tested following contexts:

- `es_version: "7.10+"`
- Setting existing ES to 8.0 and have Ansible set it to 7.10+
- Creating a new ES datasource with 7.10+
- Tested for idem potency
 
 So ready to merge I guess?

**Comment by rrey** [comment]
Thanks for testing this @markri !
The datasource is working properly after creation ? You can properly get data from it through explorer/panel/Dashboard ?

**Comment by markri** [comment]
Yup, save & test button yields green message, and dashboard stats are working fine
