### ISSUE TITLE
Datasource is broken with Grafana 9.1.0

### ISSUE THREAD

**Issue by rrey** [ansible-collections/community.grafana#272]
##### SUMMARY

Integration tests for datasource failed with Grafana 9.1.0.
This seems to be a regression in the API endpoint.

See https://github.com/grafana/grafana/issues/53995

**Comment by Nemental** [comment]
Can be closed

https://github.com/grafana/grafana/issues/53995#issuecomment-1276425832
> my tests are no more failing with `9.1.7`, closing this issue.
