### ISSUE TITLE
service account token does not work with lookup plugin grafana_dashboard

### ISSUE THREAD

**Issue by fotto** [ansible-collections/community.grafana#303]
##### SUMMARY
Using lookup plugin "grafana_dashboard" with a service account token returns 401 (Unauthorized)

https://github.com/ansible-collections/community.grafana/blob/main/plugins/lookup/grafana_dashboard.py#L118 appends '==' to all service account tokens generated with Grafana 9.2.x which makes the resulting Authorization Header invalid.

Please verify whether that logic is still applicable.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/lookup/grafana_dashboard.py

##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.14.3]
```

##### COLLECTION VERSION

```paste below
community.grafana    1.5.4
```

##### CONFIGURATION

```paste below
```

##### OS / ENVIRONMENT

Grafana 9.2.10

##### STEPS TO REPRODUCE

* create service account in Grafana 
* create service account token for new service acocunt
* use service account token and Grafana server URL in a playbook containing the snippet shown below

```yaml
  tasks:
  - name: get existing dashboards
    set_fact:
      grafana_dashboards: "{{ lookup('grafana_dashboard', 'grafana_url=' ~ grafana_server_url ~ ' grafana_api_key=' ~ grafana_api_key) }}"
  - debug:
      var: grafana_dashboards
```

##### EXPECTED RESULTS

List of defined dashboards is returned.

The expected result can be enforce by removing 118-124 from https://github.com/ansible-collections/community.grafana/blob/main/plugins/lookup/grafana_dashboard.py#L118

##### ACTUAL RESULTS

```paste below
fatal: [ansible_master]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'grafana_dashboard'. Error was a <class 'ansible_collections.community.grafana.plugins.lookup.grafana_dashboard.GrafanaAPIException'>, original message: Unable to search dashboards : HTTP Error 401: Unauthorized. Unable to search dashboards : HTTP Error 401: Unauthorized"}
```

**Comment by clasch1985** [comment]
I have a similar issue when using the  lookup plugin "grafana_dashboard".

With this task:

` - name: Get all grafana dashboards
   ansible.builtin.set_fact:
     grafana_dashboards: "{{ lookup('community.grafana.grafana_dashboard', 'grafana_url=' ~ grafana_url ~ ' grafana_api_key=' ~ grafana_api_key) }}"`

I get

`{
  "msg": "An unhandled exception occurred while running the lookup plugin 'community.grafana.grafana_dashboard'. Error was a <class 'AttributeError'>, original message: 'NoneType' object has no attribute 'get'. 'NoneType' object has no attribute 'get'",
  "_ansible_no_log": false
}`

ANSIBLE VERSION
ansible-playbook [core 2.15.10]
COLLECTION VERSION
community.grafana    2.0.0
GRAFANA VERSION
Grafana 11.1.3 (Enterprise)

But I have no idea if it is the same issue as above. Also tried with validate_certs=false and get the same results.

**Comment by fotto** [comment]
> Hi @fotto, are you still having this problem? Please let me know. 401 sounds like an authentication problem or a wrong token.

Unfortunately, I cannot easily reproduce the setup.
