### ISSUE TITLE
Merge `telekom-mms.grafana` into `community.grafana`

### ISSUE THREAD

**Issue by Nemental** [ansible-collections/community.grafana#340]
##### SUMMARY

Merge [telekom-mms.grafana](https://github.com/telekom-mms/ansible-role-grafana) in `community.grafana`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- collection roles
##### ADDITIONAL INFORMATION

As an addition to #322, I would like to suggest merging the role `telekom-mms.grafana` into the `community.grafana` collection.
@rrey @seuf What are your thoughts about that?

**Comment by rrey** [comment]
I don't see any problem with that as long as you are committed in maintaining the collection in the long term.
<3

**Comment by Nemental** [comment]
That's the plan! We came with the intention of supporting the collection long-term. 🚀
I'll discuss this internally and create a PR.
