### ISSUE TITLE
Support for nested folders.

### ISSUE THREAD

**Issue by rolatsch** [ansible-collections/community.grafana#380]
##### SUMMARY
As of version 11 Grafana supports nested folders. This would be a nice addition to the folders module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.grafana.grafana_folder

##### ADDITIONAL INFORMATION
Nesting folders works by adding a `parentUid` to the body of `POST /api/folders` request.

**Comment by Nemental** [comment]
Hi @rolatsch :) Thanks for your feature request! I will take a look at it.

**Comment by Nemental** [comment]
Hi @rolatsch - your feature request is under review and will be included in the next release. If you want, you can run some tests (branch `feat/sub-folders`).

**Comment by rolatsch** [comment]
@Nemental wow that was super quick. Thank you 😊 
I'll try to free up some time for testing in the next few days.

**Comment by rolatsch** [comment]
Sorry, it took me a little longer to test it. 
Creating the subdirectories works great. 
But the dashboard module would have to be adapted too so that it uses the folderUid parameter.
