### ISSUE TITLE
Support exporting a dashboard without its metadata (just like Grafana)

### ISSUE THREAD

**Issue by kongslund** [ansible-collections/community.grafana#94]
##### SUMMARY

Support exporting a dashboard without its metadata (just like Grafana). Metadata are only relevant for the current Grafana environment.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.grafana.grafana_dashboard

##### ADDITIONAL INFORMATION

The `export` state for the `community.grafana.grafana_dashboard` module currently results in a dashboard file consisting of a dashboard definition and some dashboard metadata specific to the current Grafana environment:

```json
{
  "dashboard": {
    <dashboard definition>
  },
  "meta": {
    <dashboard metadata>
  }
}
```

This differs from Grafana's [export functionality](https://grafana.com/docs/grafana/latest/reference/export_import/#exporting-a-dashboard) where the exported content simply consists of the dashboard definition:

```json
{
  <dashboard definition>
}
```

This output is desired when the dashboard is meant to be imported into other Grafana environments.

How should this be supported? I have two ideas:

1) Add an extra state `save` which corresponds to the current behavior. Change `export` to actually behave like Grafana's export functionality.
This is IMHO a more intuitive naming scheme. It breaks compatibility though but perhaps that's acceptable since this collection is still version 0.x.x.

2) Add a boolean flag `export_with_metadata` (or similar) which determines whether the dashboard is exported with or without metadata. This won't break compatibility if its default value is true.

Thoughts?

**Comment by rrey** [comment]
Hi @kongslund !

Sounds great to me, thanks for the details !
The first solution sounds cleaner and I think we have some code that removes the meta block in some cases. 

We could release this with a 1.x release version to mark the backward incompatibility.
@seuf any opinion on this ?

@kongslund Would you submit the Pull Request ?

**Comment by seuf** [comment]
Yes, good idea.
The module should also support the `external_use` boolean parameter introduced in Grafana 5.3.4+.

**Comment by kongslund** [comment]
> @kongslund Would you submit the Pull Request ?

I'll give it a shot

**Comment by kongslund** [comment]
I've been looking into the API and it seems to lack any export abstraction: https://grafana.com/docs/grafana/latest/http_api/dashboard/#get-dashboard-by-uid

Grafana itself has a lot of export logic that I'm not sure would be good thing to replicate.
https://github.com/grafana/grafana/blob/v7.0.1/public/app/features/dashboard/components/ShareModal/ShareExport.tsx
https://github.com/grafana/grafana/blob/v7.0.1/public/app/features/dashboard/components/DashExportModal/DashboardExporter.ts

Thoughts?

**Comment by rrey** [comment]
Hi @kongslund 
I'm not super fan of the idea to re-code a logic from Grafana in the module, I would rather prefer to use the APIs and avoid to much magic if possible.

During the import of a dashboard Json, the meta part is removed so it should not be a problem to have it in the JSON exported from the module or from the UI.

If you have an issue we have to fix it though

**Comment by rrey** [comment]
Closing this issue without feedback
